import * as types from 'config/api-type'

export default {
  [types.IDENTITY_POST]: '/user/identity/auth',
  [types.IDENTITY_FETCH]: '/user/identity/fetch/auth',
  [types.JOB_POST]: '/user/job/auth',
  [types.JOB_FETCH]: '/user/job/fetch/auth',
  [types.CONTACT_POST]: '/user/contact/auth',
  [types.CONTACT_FETCH]: '/user/contact/fetch/auth',
  [types.BANK]: '/user/bank/auth',
  [types.BANK_LIST]: '/user/bank-list/auth',
  [types.SMSCODE]: '/user/smscode',
  [types.SCORE_FETCH]: '/user/score/fetch/auth',
  [types.SCORE]: '/user/score/auth',
  [types.EXTEND_SAVE]: '/user/userExtend/saveOrUpdate/auth',
  [types.EXTEND_QUERY]: '/user/userExtend/query/auth',
  [types.FETCH_EVALUATE_SCORE]: '/user/evaluateScore/auth',
  [types.CHECK_NAME]: '/user/checkName/auth',
  [types.BASEINFO_SAVE]: '/user/baseInfo/auth',
  [types.BASEINFO_QUERY]: '/user/baseInfo/fetch/auth',
  [types.BORROW]: '/order/borrow/auth',
  [types.BORROW_CONFIRM]: '/order/borrow/confirm/auth',
  [types.BORROW_RESULT]: '/order/borrow/result/auth',
  [types.BORROW_DETAIL]: '/order/borrow/detail/auth',
  [types.BORROW_RECORD]: '/order/borrow/record/auth',
  [types.INTELLIGENT_RECOMMEND]: '/order/borrow/auth',
  [types.PRODUCT_DOWNLOAD]: '/order/download/auth',
  [types.AUDIT_FLOW]: '/order/audit/flow/auth',
  [types.GENERATE_REPEAT]: '/order/generateRepeat/auth',
  [types.BORROW_FAIL]: '/order/borrow/audit/fail',
  [types.GET_REPAYMENT_TIP]: '/zeus/bill',
  [types.REPAY_SCHEDULE]: '/zeus/bill-list',
  [types.USER_CONTRACT]: '/application/agreement',
  [types.FETCH_ASSESS_FEE]: '/application/fetch/assessFee',
  [types.VIP]: '/member/fetch',
  [types.QUIKPAY]: '/pay/hlb/quikPayYmt',
  [types.DIRECTPAY]: '/pay/hlb/directPay',
  [types.ALI_APPPAY]: '/pay/ali/appPay',
  [types.BILL_HELIBAO]: '/zeus/bill/helibao',
  [types.GXB_TOKEN]: '/dsp/api/resource/gxb/token'
}
